#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=":" read -r user password uid gid info home command
do
	echo "The user ${user} is part of the ${gid} gang, lives in ${home} and rides ${command}. ${uid}'s place is protected by the passcode ${password}, more info about the user here: ${info}"
done </etc/passwd
