#!/usr/bin/env bash
#displays : 
#	    The content of the current directory
#	    In a list format
#	    Where only the part of the name after the first dash is displayed

for content in *
do
	name=$(echo "$content" | cut -d "-" -f 2)
	echo "$name"
done
